### ISSUE TITLE
GDAL fallback to vsicurl

### ISSUE THREAD

**Issue by thomascoquet** [airbusgeo/osio#14]
Hello Thomas,

I noticed in some cases GDAL is falling back to VSICurl when using `osio`. Not sure exactly where to start looking,  I had no success in GDAL code base looking for such pattern.

Summary is that when `osio` returns a 403 (with the `geosjon` driver enabled, I cannot explain that), GDAL seems to be falling back to `vsicurl` (or `vsicurl_streaming`) and downloads the entire GeoTIFF file.

---

Given the following:

```go
func TestHead(t *testing.T) {
	ctx := context.Background()
	hdl, _ := osio.HTTPHandle(ctx)
	key := "https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx"

	// godal
	godal.RegisterRaster(godal.GTiff)
	//godal.RegisterVector(godal.GeoJSON)
	adp, _ := osio.NewAdapter(hdl)
	godal.RegisterVSIHandler("http://", adp)
	godal.RegisterVSIHandler("https://", adp)

	// open
	_, err := godal.Open(key)
	assert.Nil(t, err)
}
```

Here is what I see (adding some logs in `http.go`):
```
request [off: 0, len: 131072] https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx
head request [err: <nil>, status: 403]

request [off: 0, len: 131072] https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx
head request [err: <nil>, status: 403]
```
Basically, S3 returns 403 for the HEAD request and the code is logically failing.

---

*However*, when including the GeoJSON driver:

```go
func TestHead(t *testing.T) {
	ctx := context.Background()
	hdl, _ := osio.HTTPHandle(ctx)
	key := "https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx"

	// godal
	godal.RegisterRaster(godal.GTiff)
	godal.RegisterVector(godal.GeoJSON)
	adp, _ := osio.NewAdapter(hdl)
	godal.RegisterVSIHandler("http://", adp)
	godal.RegisterVSIHandler("https://", adp)

	// open
	_, err := godal.Open(key)
	assert.Nil(t, err)
}
```
Here is what I am seeing:
```
request [off: 0, len: 131072] https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx
head request [err: <nil>, status: 403]

request [off: 0, len: 131072] https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx
head request [err: <nil>, status: 403]

GDAL: HTTP: Fetch(https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx)
GDAL: HTTP: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
GDAL: HTTP: These HTTP headers were set: Accept: text/plain, application/json
* Couldn't find host sentinel-s1-l1c.s3.amazonaws.com in the .netrc file; using defaults
*   Trying 52.219.171.111...
* TCP_NODELAY set
* Connected to sentinel-s1-l1c.s3.amazonaws.com (52.219.171.111) port 443 (#0)
* found 128 certificates in /etc/ssl/certs/ca-certificates.crt
* found 387 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.s3.amazonaws.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=*.s3.amazonaws.com
*        start date: Wed, 15 Dec 2021 00:00:00 GMT
*        expire date: Sat, 03 Dec 2022 23:59:59 GMT
*        issuer: C=US,O=Amazon,OU=Server CA 1B,CN=Amazon
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET https://sentinel-s1-l1c.s3.amazonaws.com/GRD/2021/1/16/IW/DV/S1A_IW_GRDH_1SDV_20210116T002753_20210116T002818_036156_043D3C_9576/measurement/iw-vv.tiff?X-Amz-Signature=xxx
 HTTP/1.1
Host: sentinel-s1-l1c.s3.amazonaws.com
Accept-Encoding: gzip
Accept: text/plain, application/json

< HTTP/1.1 200 OK
< x-amz-id-2: xxx
< x-amz-request-id: xxx
< Date: Thu, 10 Feb 2022 10:32:57 GMT
< x-amz-request-charged: requester
< Last-Modified: Sat, 06 Mar 2021 01:34:22 GMT
< ETag: "xxx"
< x-amz-storage-class: INTELLIGENT_TIERING
< Accept-Ranges: bytes
< Content-Type: image/tiff
< Server: AmazonS3
< Content-Length: 684991437
< 
```

The issue here is that GDAL is downloading the whole file (no range request as you can see in the logs) whereas `osio` returned a 403.

---

Happy to file an issue at osgeo/gdal if you think it is more appropriate and not due to osio behavior.

Thomas

**Comment by thomascoquet** [comment]
[NB: I have not mentioned it but I will create a MR to get the same behavior as GDAL with HEAD/GET to get file size in case where HEAD is not allowed. Should fix the symptoms but probably not the root cause.]

**Comment by tbonfort** [comment]
In https://github.com/OSGeo/gdal/blob/ab2e741bb78f9d5fce109d5b89d5b207430f4e0e/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L527 , the gdal geojson driver will identify the url as being a potential geojson-service. In https://github.com/OSGeo/gdal/blob/ab2e741bb78f9d5fce109d5b89d5b207430f4e0e/ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp#L111 it will then be loaded via `CPLHTTPFetch`. As a workaround in your case, you can either force gdal.Open to only consider raster drivers (`RasterOnly()`) , or explicitely use the GTiff driver only. This might be an issue to raise with gdal itself.

**Comment by tbonfort** [comment]
closing as this is not related to osio

**Comment by thomascoquet** [comment]
Thanks for the workaround, works perfectly!
I guess I misunderstood how the VSI handler provided by `osio` worked ; I thought it was responsible for all IO if a key matched a given prefix, no matter the driver used under the hood.
I'll file a ticket to gdal.

**Comment by tbonfort** [comment]
> I thought it was responsible for all IO if a key matched a given prefix, no matter the driver used under the hood.

Yes that's how it's supposed to work for all *file* accesses, however it does not prevent specific drivers from bypassing that e.g. for very good reasons when interacting with ogc wxs services, and/or for historical or interoperability reasons in the case of geojson.
